
(() => {
  const App = window.AITradeX, Auth = window.AITradeXAuth, root = document.getElementById("app");
  let page = "home", authMode = "login", accountMode = localStorage.getItem("AITradeX_ACCOUNT_MODE") || "REAL";
  let drawerOpen = false, autoPercent = Number(localStorage.getItem("AITradeX_AUTO_PERCENT") || 25);
  let autoTradeOn = localStorage.getItem("AITradeX_AUTO_ON") === "true";
  const pairs = [{p:"BTC/USDT",r:"$76,737.55",c:"-0.69%"},{p:"ETH/USDT",r:"$2,111.72",c:"-1.04%"},{p:"SOL/USDT",r:"$84.46",c:"-0.60%"},{p:"BNB/USDT",r:"$639.82",c:"-0.28%"}];
  const lev = [1,5,10,20,50,100,200,500,1000,2000];
  const bal = () => { const u=App.currentUser(); return !u?0:(accountMode==="DEMO"?App.demoBalance(u.id):App.realBalance(u.id)); };
  const pnl = () => { const u=App.currentUser(); return !u?0:App.state.trades.filter(t=>t.userId===u.id && t.accountType===accountMode && t.status==="CLOSED").reduce((s,t)=>s+Number(t.pnl||0),0); };
  const av = n => `<span class="avatar">${String(n||"A").trim().charAt(0).toUpperCase()}</span>`;
  const st = (t,s="") => `<div class="mobile-section-title"><p>${s}</p><h2>${t}</h2></div>`;
  function header(u){return `<header class="app-topbar"><button class="menu-btn" onclick="AITradeXUser.toggleDrawer()">☰</button><div class="app-brand">AITradeX</div><div class="top-actions"><button class="account-switch ${accountMode.toLowerCase()}" onclick="AITradeXUser.toggleAccountMode()">${accountMode==="REAL"?"Real":"Demo"}</button><button class="profile-chip" onclick="AITradeXUser.toggleDrawer()">${av(u.name)}<b>${App.escapeHtml(u.name||"User")}</b></button></div></header>${drawerOpen?drawer(u):""}`;}
  function drawer(){return `<div class="drawer-backdrop" onclick="AITradeXUser.toggleDrawer(false)"></div><aside class="side-drawer"><button onclick="AITradeXUser.go('profile')" class="drawer-item">👤 Profile</button><button onclick="AITradeXUser.go('kyc')" class="drawer-item">🛡️ KYC Verification</button><button onclick="AITradeXUser.go('referral')" class="drawer-item">🎁 Referral</button><button onclick="AITradeXUser.go('payments')" class="drawer-item">💳 My Payment Methods</button><button onclick="AITradeXUser.go('support')" class="drawer-item">🎧 Support</button><button onclick="AITradeXUser.logout()" class="drawer-item danger">🚪 Logout</button></aside>`;}
  function nav(){return `<nav class="bottom-nav">${[["home","⌂","Home"],["trade","⇅","Trade"],["wallet","▣","Wallet"],["pnl","↗","PnL"],["history","☰","History"]].map(x=>`<button class="${page===x[0]?"active":""}" onclick="AITradeXUser.go('${x[0]}')"><i>${x[1]}</i><span>${x[2]}</span></button>`).join("")}</nav>`;}
  function shell(c){const u=App.currentUser(); root.innerHTML=`<div class="mobile-app">${header(u)}<main class="mobile-content">${c}</main>${nav()}</div>`;}
  function landing(){root.innerHTML=`<main class="public-wrap"><nav class="public-nav"><div class="brand"><span>AI</span><b>AITradeX</b></div><div class="public-actions"><a href="#plans">Plans</a><a href="#security">Security</a><button onclick="AITradeXUser.scrollAuth()" class="btn small">Get Started</button></div></nav><section class="hero-section"><div class="hero-copy"><p class="eyebrow">AI Real Trading Platform</p><h1>AI powered trading experience with secure INR wallet.</h1><p class="hero-text">AITradeX combines a premium trading dashboard, TradingView style charts, real and demo account modes, KYC verification, subscriptions, referrals and a clean wallet ledger.</p><div class="hero-buttons"><button onclick="AITradeXUser.scrollAuth()" class="btn">Create Account</button><button onclick="AITradeXUser.setAuthMode('login')" class="btn ghost">User Login</button></div><div class="trust-pills"><span>KYC Verified</span><span>INR Wallet</span><span>Real + Demo</span></div></div><div class="hero-terminal"><div class="terminal-head"><div><span>BTC/USDT</span><strong>₹58,42,210</strong></div><em>+2.84%</em></div><div class="fake-chart"></div><div class="terminal-grid"><div><span>AI Signal</span><b>BUY</b></div><div><span>Leverage</span><b>2000x</b></div><div><span>Risk</span><b>Adaptive</b></div></div></div></section><section id="plans" class="landing-grid"><article><i>💰</i><h3>Secure Wallet</h3><p>Deposit, withdrawal, pending funds and ledger-based balance.</p></article><article><i>📈</i><h3>AI Trading</h3><p>Buy/Sell, pairs, amount, leverage up to 2000x, real and demo accounts.</p></article><article><i>🤝</i><h3>Referral</h3><p>10% one-time commission only on first approved deposit.</p></article></section><section id="authBox" class="auth-section"><div class="auth-copy"><p class="eyebrow">User Access</p><h2>${authMode==="login"?"Login to AITradeX":"Create AITradeX account"}</h2><p>User panel is fully separate from the control center. No control wording is shown here.</p></div><div class="auth-card"><div class="auth-tabs"><button class="${authMode==="login"?"active":""}" onclick="AITradeXUser.setAuthMode('login')">Login</button><button class="${authMode==="register"?"active":""}" onclick="AITradeXUser.setAuthMode('register')">Register</button></div>${authMode==="login"?loginForm():registerForm()}</div></section><section id="security" class="security-note"><b>AITradeX Security:</b> KYC approval and verified payment methods help reduce fraud risk before withdrawals.</section></main>`;}
  function loginForm(){return `<form onsubmit="AITradeXUser.login(event)" class="form-grid"><label>Email<input id="loginEmail" type="email" required placeholder="you@example.com"/></label><label>Password<input id="loginPassword" type="password" required placeholder="Password"/></label><button class="btn">Login</button></form>`;}
  function registerForm(){return `<form onsubmit="AITradeXUser.register(event)" class="form-grid"><label>Full Name<input id="regName" required placeholder="Your name"/></label><label>Email<input id="regEmail" type="email" required placeholder="you@example.com"/></label><label>Mobile<input id="regMobile" required placeholder="10 digit mobile"/></label><label>Password<input id="regPassword" type="password" required placeholder="Create password"/></label><label>Referral Code <small>Optional</small><input id="regReferral" placeholder="Referral code"/></label><button class="btn">Create Account</button></form>`;}
  function home(){const u=App.currentUser(), amount=bal()*autoPercent/100; shell(`<section class="welcome-card"><div><p>WELCOME BACK</p><h1>Hello, ${App.escapeHtml(u.name||"User")}</h1></div>${av(u.name)}<div class="account-boxes"><article><span>Demo Account</span><b>${App.money(App.demoBalance(u.id))}</b></article><article class="active"><span>Real Account</span><b>${App.money(App.realBalance(u.id))}</b></article></div></section><section class="coin-grid">${pairs.map(p=>`<article class="coin-card"><h3>${p.p}</h3><b>${p.r}</b><span>${p.c}</span></article>`).join("")}</section><section class="coin-grid"><article class="coin-card stat"><span>Today PnL</span><strong>${App.money(pnl())}</strong></article><article class="coin-card stat"><span>Win Rate</span><strong>0%</strong></article><article class="coin-card stat"><span>Market Mood</span><strong>Neutral</strong></article><article class="coin-card stat"><span>Active Signal</span><strong>BUY</strong></article></section><section class="signal-card"><div class="signal-dot"></div><p>AI SIGNAL LIVE</p><h2>BUY BTC/USDT</h2><h4>AI trend confirmation active.</h4><div class="signal-percent">82%</div><div class="signal-grid"><article><span>Entry</span><b>Market</b></article><article><span>Target</span><b>-</b></article><article><span>Stop Loss</span><b>-</b></article><article><span>Expires</span><b>30m</b></article></div></section><section class="signal-card auto-card"><p>AI TRADE CONTROL</p><h2>AI Auto Trade Amount</h2><h4>AITradeX selected ${accountMode} balance ke percentage se trade karega.</h4><div class="percent-grid">${[25,50,75,100].map(v=>`<button class="${autoPercent===v?"active":""}" onclick="AITradeXUser.setAutoPercent(${v})">${v}%</button>`).join("")}</div><div class="selected-box"><span>Selected</span><b>${autoPercent}%</b><p>AI trade amount: ${App.money(amount)}</p></div><div class="toggle-row"><div><b>Auto AI Trade</b><span>Allow AI trades from platform signals</span></div><button class="toggle ${autoTradeOn?"on":""}" onclick="AITradeXUser.toggleAutoTrade()"><i></i></button></div></section>`);}
  function trade(){shell(`${st("BTC/USDT",accountMode+" ACCOUNT · TRADING")}<section class="chart-panel"><div class="live-badge">LIVE</div><div class="full-chart-frame"><div class="chart-toolbar">1m&nbsp;&nbsp; 30m&nbsp;&nbsp; 1h&nbsp;&nbsp; ⚙ &nbsp;&nbsp; +</div><div class="candle-chart"></div></div></section><section class="order-card"><p>ORDER TICKET</p><h2>Place Buy/Sell Order</h2><label>Coin<select><option>BTC/USDT</option><option>ETH/USDT</option><option>SOL/USDT</option><option>BNB/USDT</option></select></label><div class="form-row"><label>Order Type<select><option>Market</option><option>Limit</option></select></label><label>Leverage<select>${lev.map(x=>`<option>${x}x</option>`).join("")}</select></label></div><label>Margin Amount<input type="number" placeholder="100"/></label><div class="form-row"><label>Take Profit Optional<input placeholder="TP price"/></label><label>Stop Loss Optional<input placeholder="SL price"/></label></div><div class="buy-sell-row"><button class="buy-btn">BUY / LONG</button><button class="sell-btn">SELL / SHORT</button></div></section><section class="order-card"><p>ORDER BOOK</p><h2>BTC/USDT Depth</h2><span class="mini-live">LIVE</span><div class="order-table"><span>Price</span><span>Qty</span><span>Total</span><b class="red">$77,147.07</b><b>1.5562</b><b>$120,057.35</b><b class="red">$77,104.78</b><b>0.2684</b><b>$20,691.43</b><b class="red">$77,062.49</b><b>0.3581</b><b>$27,594.27</b></div></section><section class="order-card"><p>LIVE TRADES</p><h2>Open Positions</h2><div class="empty-box">No open positions.</div></section>`);}
  function wallet(){const u=App.currentUser(),real=App.realBalance(u.id),cur=accountMode==="REAL"?real:App.demoBalance(u.id); shell(`<section class="wallet-hero"><p>WALLET</p><h1>${accountMode==="REAL"?"Real Wallet Equity":"Demo Wallet Equity"}</h1><strong>${App.money(cur)}</strong><span>LIVE</span></section><section class="wallet-grid"><article><span>💰 Available Balance</span><b>${App.money(cur)}</b><p>Funds ready for trade</p></article><article><span>🏦 Withdrawable Balance</span><b>${accountMode==="REAL"?App.money(real):"Not available"}</b><p>Available for withdrawal</p></article><article><span>⏳ Pending Deposit</span><b>${App.money(App.pendingDeposit(u.id))}</b><p>Waiting for approval</p></article><article><span>⏳ Pending Withdrawal</span><b>${App.money(App.pendingWithdrawal(u.id))}</b><p>Under review</p></article></section>${accountMode==="REAL"?`<section class="wallet-actions"><button>Deposit</button><button>Withdrawal</button><button>History</button></section><section class="order-card"><p>ADD FUNDS</p><h2>Deposit Step Flow</h2><div class="empty-box">Step 1 Amount → Step 2 Mode → Step 3 Pay with UPI QR/Bank → Step 4 UTR</div></section>`:`<section class="order-card"><p>DEMO WALLET</p><h2>Practice Mode</h2><div class="empty-box">Demo wallet is for practice trading only. Deposit and withdrawal are available in Real Account.</div></section>`}`);}
  function simple(t,sub,body){shell(`<section class="order-card"><p>${sub}</p><h2>${t}</h2><div class="empty-box">${body}</div></section>`);}
  function pnlPage(){shell(`<section class="coin-grid"><article class="coin-card stat"><span>Total Trades</span><strong>0</strong></article><article class="coin-card stat"><span>Total PnL</span><strong>${App.money(pnl())}</strong></article><article class="coin-card stat"><span>Win Rate</span><strong>0%</strong></article><article class="coin-card stat"><span>Referral Bonus</span><strong>₹0</strong></article></section><section class="order-card"><p>PNL ANALYTICS</p><h2>Performance Overview</h2><div class="empty-box">PnL graph and analytics will be connected in next phases.</div></section>`);}
  function history(){shell(`<section class="order-card"><p>AI / AI TRADES</p><h2>Closed AI Trade History</h2><div class="history-card"><span>Coin</span><b>BTC/USDT</b><span>Side</span><b>BUY</b><span>Amount</span><b>₹10,000</b><span>Entry</span><b>$76,828</b><span>Close</span><b>$76,838</b><span>PnL</span><b class="green">₹1.3</b><span>Status</span><b>CLOSED</b></div></section><section class="order-card"><p>MANUAL TRADES</p><h2>Your Manual Trade History</h2><div class="empty-box">Manual open and closed trades will appear here.</div></section>`);}
  function render(){const u=App.currentUser(); if(!u||u.role!=="user")return landing(); if(page==="home")return home(); if(page==="trade")return trade(); if(page==="wallet")return wallet(); if(page==="pnl")return pnlPage(); if(page==="history")return history(); if(page==="kyc")return simple("4 Step Verification","KYC VERIFICATION","Step 1 Personal → Step 2 ID Details → Step 3 ID Card + Selfie Upload → Step 4 Review"); if(page==="payments")return simple("My Payment Methods","PAYMENT METHODS","Holder name will auto-fill from approved KYC. Max 2 UPI and 2 Bank accounts."); if(page==="referral")return simple("Invite & Earn","REFERRAL",`Your referral code: <b>${u.referralCode||"-"}</b><br/>10% commission only on first approved deposit.`); if(page==="profile")return simple(App.escapeHtml(u.name),"PROFILE",`${App.escapeHtml(u.email)}<br/>${App.escapeHtml(u.mobile||"")}`); if(page==="support")return simple("Help Center","SUPPORT","Support tickets will be connected in later phase."); return home();}
  window.AITradeXUser={setAuthMode(m){authMode=m;landing();setTimeout(()=>document.getElementById("authBox")?.scrollIntoView({behavior:"smooth"}),50)},scrollAuth(){document.getElementById("authBox")?.scrollIntoView({behavior:"smooth"})},register(e){e.preventDefault();try{Auth.registerUser({name:regName.value,email:regEmail.value,mobile:regMobile.value,password:regPassword.value,referralCode:regReferral.value.trim()});page="home";App.toast("Account created successfully.");render()}catch(err){App.toast(err.message)}},login(e){e.preventDefault();try{Auth.loginUser({email:loginEmail.value,password:loginPassword.value});page="home";App.toast("Logged in successfully.");render()}catch(err){App.toast(err.message)}},go(p){page=p;drawerOpen=false;render()},toggleDrawer(f){drawerOpen=typeof f==="boolean"?f:!drawerOpen;render()},toggleAccountMode(){accountMode=accountMode==="REAL"?"DEMO":"REAL";localStorage.setItem("AITradeX_ACCOUNT_MODE",accountMode);render()},setAutoPercent(v){autoPercent=Number(v);localStorage.setItem("AITradeX_AUTO_PERCENT",autoPercent);render()},toggleAutoTrade(){autoTradeOn=!autoTradeOn;localStorage.setItem("AITradeX_AUTO_ON",String(autoTradeOn));render()},logout(){App.clearSession();page="home";drawerOpen=false;landing()}};
  render();
})();
